version: "3.8"
services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: property_extractor
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - property_extractor_data:/var/lib/postgresql/data

volumes:
  property_extractor_data:
